name: deploy-dev

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  testing:
    uses: ./.github/workflows/testing.yml
    with:
      environment: dev
    secrets: inherit
    

  deploy:
    needs: testing
    name: 'Deploy bundle'

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dabs_prof_cert
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Databricks CLI Setup
        uses: databricks/setup-cli@v0.285.0

      - name: Deploy bundle
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        run: databricks bundle deploy -t dev

  create-pull-request:
    name: 'Create Pull Request from Dev to Master'
    needs: deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0   # important for branches

    - name: create pull request
      run: gh pr create -B dev -H master --title 'Merge dev into master' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ github.token }}