# name: Create PR from Dev to Master

# on:
#   workflow_call:
#     inputs:
#       environment:
#         required: true
#         type: string


# jobs:
#     create-pull-request:
#         name: 'Create Pull Request from Dev to Master'
#         needs: deploy
#         runs-on: ubuntu-latest
#         steps:
#         - name: create pull request
#         run: gh pr create -B dev -H master --title 'Merge dev into master' --body 'Created by Github action'
#         env:
#             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}